// Token estimation without a tokenizer.
//
// A real BPE tokenizer needs a multi-megabyte vocabulary, and this site never
// touches the network, so exact counts aren't available here. Instead the text
// is split the way a tokenizer's pre-tokenizer splits it — runs of letters,
// digits, whitespace and symbols — and each run is priced from its length and
// script. On English prose and source code that lands within roughly 10% of a
// real count, which is enough to size a prompt or a budget. For an exact number,
// Anthropic's /v1/messages/count_tokens endpoint is authoritative.

// One run per class: letters (with combining marks), digits, whitespace, or
// everything else — punctuation, symbols, emoji.
const RUN = /[\p{L}\p{M}]+|\p{N}+|\s+|[^\s\p{L}\p{M}\p{N}]+/gu;

// Kana, Han (including extension A and compatibility) and Hangul.
const IDEOGRAPHIC = /[぀-ヿ㐀-䶿一-鿿豈-﫿ᄀ-ᇿ가-힯]/;
const PICTOGRAPH = /\p{Extended_Pictographic}/u;

export const TOKEN_CLASSES = {
  words: 'Words',
  numbers: 'Numbers',
  symbols: 'Symbols & punctuation',
  spacing: 'Whitespace & newlines',
  ideographic: 'CJK & Hangul',
};

function classOf(run) {
  if (/^\s+$/.test(run)) return 'spacing';
  if (/^\p{N}+$/u.test(run)) return 'numbers';
  if (/^[\p{L}\p{M}]+$/u.test(run)) return IDEOGRAPHIC.test(run) ? 'ideographic' : 'words';
  return 'symbols';
}

// A latin word of up to seven letters is nearly always one token; longer ones
// break into roughly four-letter pieces.
const subwordCost = (length) => (length <= 7 ? 1 : 1 + Math.ceil((length - 7) / 4));

// Case boundaries split first, so `getUserName` prices as three pieces and
// `parseHTTPResponse` as three too, rather than as one long run.
const splitCase = (run) => run
  .replace(/([\p{Ll}\p{N}])(\p{Lu})/gu, '$1 $2')
  .replace(/(\p{Lu}+)(\p{Lu}\p{Ll})/gu, '$1 $2')
  .split(' ');

const wordCost = (run) => splitCase(run).reduce((total, part) => total + subwordCost(part.length), 0);

// Digits group in threes, the way thousands separators fall.
const numberCost = (run) => Math.ceil(run.length / 3);

// Indentation and blank-line runs collapse into very few tokens. A lone space
// merges into the word after it and costs nothing, but a line break is always
// worth at least one token.
function spacingCost(run) {
  const chunks = Math.ceil(run.length / 6);
  if (/[\r\n]/.test(run)) return Math.max(1, chunks);
  return run.length <= 1 ? 0 : chunks;
}

// Symbol runs pack about two characters per token (`);`, `=>`, `**`); emoji are
// far denser, at a few tokens each.
function symbolCost(run) {
  const pictographs = [...run].filter((character) => PICTOGRAPH.test(character)).length;
  return pictographs * 2 + Math.ceil((run.length - pictographs) / 2);
}

// Han, kana and Hangul run a little over one token per character.
const ideographicCost = (run) => Math.ceil(run.length * 1.2);

const COST = {
  words: wordCost,
  numbers: numberCost,
  symbols: symbolCost,
  spacing: spacingCost,
  ideographic: ideographicCost,
};

/**
 * Estimate how many tokens `text` would use.
 * @returns {{ tokens: number, breakdown: Record<string, number> }}
 */
export function estimateTokens(text) {
  const breakdown = { words: 0, numbers: 0, symbols: 0, spacing: 0, ideographic: 0 };
  for (const [run] of text.matchAll(RUN)) {
    const group = classOf(run);
    breakdown[group] += COST[group](run);
  }
  const tokens = Object.values(breakdown).reduce((total, count) => total + count, 0);
  return { tokens, breakdown };
}

// Prices in US dollars per million tokens, generated by scripts/update-prices.mjs
// from two independent feeds that had to agree. Bundled at build time, so the
// page still makes no network calls — run `npm run prices` to refresh.
import priceTable from './prices.json';

export const MODELS = priceTable.models;
export const PRICES_AS_OF = priceTable.fetchedAt;
